# Uncomment the next line to define a global platform for your project
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '11.0'

target 'Mattermost' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Mattermost
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])  
  permissions_path = "../node_modules/react-native-permissions/ios"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera/Permission-Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary/Permission-PhotoLibrary.podspec"
  pod 'XCDYouTubeKit', '2.8.2'
  pod 'Swime', '3.0.6'
  # Pods for Mattermost

end
